package vista;

import java.awt.Dimension;
import java.util.List;
import java.awt.Toolkit;
import java.time.Instant;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.JOptionPane;
import modelo.Reserva;
import modelo.TipoEvento;

public class PantallaSecundaria extends javax.swing.JDialog {

    public static String EVENTO = "Congreso";
    private boolean reservaRealizada = false;

    public PantallaSecundaria(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
        int width = this.getSize().width;
        int height = this.getSize().height;
        int xPos = (pantalla.width - width) / 2;
        int yPos = (pantalla.height - height) / 2;
        this.setLocation(xPos, yPos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        labelTituloReservaSalon = new javax.swing.JLabel();
        jPanelDatosPersonalesReserva = new javax.swing.JPanel();
        labelDatosPersonalesReserva = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        labelTelefono = new javax.swing.JLabel();
        labelNumeroDias = new javax.swing.JLabel();
        labelNumeroHabitaciones = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldTelefono = new javax.swing.JTextField();
        jSpinnerNumeroDias = new javax.swing.JSpinner();
        jSpinnerNumeroHabitaciones = new javax.swing.JSpinner();
        jPanelEvento = new javax.swing.JPanel();
        labelEvento = new javax.swing.JLabel();
        labelFechaEvento = new javax.swing.JLabel();
        labelTipoEvento = new javax.swing.JLabel();
        labelNumeroAsistentes = new javax.swing.JLabel();
        labelTipoCocina = new javax.swing.JLabel();
        jSpinnerFecha = new javax.swing.JSpinner();
        jComboBoxTipoEvento = new javax.swing.JComboBox<>();
        jSpinnerNumeroAsistentes = new javax.swing.JSpinner();
        jScrollPaneTipoCocina = new javax.swing.JScrollPane();
        jListTipoCocina = new javax.swing.JList<>();
        labelJornadasCongreso = new javax.swing.JLabel();
        SpinnerJornadasCongreso = new javax.swing.JSpinner();
        labelAsistentes = new javax.swing.JLabel();
        jRadioButtonSiHabitaciones = new javax.swing.JRadioButton();
        jRadioButtonNoHabitaciones = new javax.swing.JRadioButton();
        jButtonRealizarReserva = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reservas La Habana");
        setPreferredSize(new java.awt.Dimension(750, 750));

        labelTituloReservaSalon.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelTituloReservaSalon.setText("RESERVA SALÓN LA HABANA");
        labelTituloReservaSalon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelDatosPersonalesReserva.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelDatosPersonalesReserva.setText("Datos personales reserva");

        labelNombre.setText("Nombre");

        labelTelefono.setText("Teléfono");

        labelNumeroDias.setText("Número de días");

        labelNumeroHabitaciones.setText("Número de habitaciones");

        jTextFieldNombre.setToolTipText("Escriba aquí su nombre completo");

        jTextFieldTelefono.setToolTipText("Escriba aquí su número de teléfono");

        jSpinnerNumeroDias.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        jSpinnerNumeroDias.setToolTipText("Seleccione el número de días del evento");

        jSpinnerNumeroHabitaciones.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        jSpinnerNumeroHabitaciones.setToolTipText("Seleccione el número de habitaciones que necesitará");

        javax.swing.GroupLayout jPanelDatosPersonalesReservaLayout = new javax.swing.GroupLayout(jPanelDatosPersonalesReserva);
        jPanelDatosPersonalesReserva.setLayout(jPanelDatosPersonalesReservaLayout);
        jPanelDatosPersonalesReservaLayout.setHorizontalGroup(
            jPanelDatosPersonalesReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosPersonalesReservaLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanelDatosPersonalesReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDatosPersonalesReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelDatosPersonalesReservaLayout.createSequentialGroup()
                        .addGroup(jPanelDatosPersonalesReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(labelNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelDatosPersonalesReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75)
                        .addGroup(jPanelDatosPersonalesReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelDatosPersonalesReservaLayout.createSequentialGroup()
                                .addComponent(labelNumeroDias, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jSpinnerNumeroDias, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelDatosPersonalesReservaLayout.createSequentialGroup()
                                .addComponent(labelNumeroHabitaciones)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSpinnerNumeroHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanelDatosPersonalesReservaLayout.setVerticalGroup(
            jPanelDatosPersonalesReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosPersonalesReservaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelDatosPersonalesReserva)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanelDatosPersonalesReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombre)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNumeroDias, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerNumeroDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosPersonalesReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTelefono)
                    .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNumeroHabitaciones)
                    .addComponent(jSpinnerNumeroHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13))
        );

        labelEvento.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelEvento.setText("Evento");

        labelFechaEvento.setText("Fecha");

        labelTipoEvento.setText("Tipo de evento");

        labelNumeroAsistentes.setText("Nº de asistentes");

        labelTipoCocina.setText("Tipo de cocina");

        jSpinnerFecha.setModel(new javax.swing.SpinnerDateModel());
        jSpinnerFecha.setToolTipText("Seleccione la fecha de inicio del evento");

        jComboBoxTipoEvento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Banquete", "Jornada", "Congreso" }));
        jComboBoxTipoEvento.setToolTipText("Seleccione el tipo de evento");
        jComboBoxTipoEvento.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxTipoEventoItemStateChanged(evt);
            }
        });

        jSpinnerNumeroAsistentes.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        jSpinnerNumeroAsistentes.setToolTipText("Seleccione cuántos asistentes asistirán al evento");

        jListTipoCocina.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Bufé", "Carta", "Cita con el chef", "No precisa" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListTipoCocina.setToolTipText("Seleccione el tipo de cocina que precisará el día del evento");
        jScrollPaneTipoCocina.setViewportView(jListTipoCocina);

        labelJornadasCongreso.setText("Nº jornadas del congreso");
        labelJornadasCongreso.setEnabled(false);

        SpinnerJornadasCongreso.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        SpinnerJornadasCongreso.setToolTipText("Seleccione el número de jornadas del congreso");
        SpinnerJornadasCongreso.setEnabled(false);

        labelAsistentes.setText("¿Los asistentes necesitarán habitaciones?");
        labelAsistentes.setEnabled(false);

        buttonGroup1.add(jRadioButtonSiHabitaciones);
        jRadioButtonSiHabitaciones.setText("Sí");
        jRadioButtonSiHabitaciones.setToolTipText("");
        jRadioButtonSiHabitaciones.setEnabled(false);

        buttonGroup1.add(jRadioButtonNoHabitaciones);
        jRadioButtonNoHabitaciones.setText("No");
        jRadioButtonNoHabitaciones.setEnabled(false);

        javax.swing.GroupLayout jPanelEventoLayout = new javax.swing.GroupLayout(jPanelEvento);
        jPanelEvento.setLayout(jPanelEventoLayout);
        jPanelEventoLayout.setHorizontalGroup(
            jPanelEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEventoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEventoLayout.createSequentialGroup()
                        .addGroup(jPanelEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelEventoLayout.createSequentialGroup()
                                .addGroup(jPanelEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelNumeroAsistentes, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelTipoCocina, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSpinnerNumeroAsistentes, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPaneTipoCocina, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanelEventoLayout.createSequentialGroup()
                                .addComponent(labelFechaEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSpinnerFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(71, 71, 71)
                        .addGroup(jPanelEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelEventoLayout.createSequentialGroup()
                                .addComponent(labelAsistentes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRadioButtonSiHabitaciones)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonNoHabitaciones)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanelEventoLayout.createSequentialGroup()
                                .addGroup(jPanelEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labelTipoEvento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelJornadasCongreso, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                                .addGap(27, 27, 27)
                                .addGroup(jPanelEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jComboBoxTipoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SpinnerJornadasCongreso, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(38, Short.MAX_VALUE))))
                    .addGroup(jPanelEventoLayout.createSequentialGroup()
                        .addComponent(labelEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanelEventoLayout.setVerticalGroup(
            jPanelEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEventoLayout.createSequentialGroup()
                .addComponent(labelEvento)
                .addGap(41, 41, 41)
                .addGroup(jPanelEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFechaEvento)
                    .addComponent(jSpinnerFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTipoEvento)
                    .addComponent(jComboBoxTipoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNumeroAsistentes)
                    .addComponent(jSpinnerNumeroAsistentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelJornadasCongreso)
                    .addComponent(SpinnerJornadasCongreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTipoCocina)
                    .addGroup(jPanelEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelAsistentes)
                        .addComponent(jRadioButtonNoHabitaciones)
                        .addComponent(jRadioButtonSiHabitaciones))
                    .addComponent(jScrollPaneTipoCocina, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jButtonRealizarReserva.setText("Realizar reserva");
        jButtonRealizarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRealizarReservaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelDatosPersonalesReserva, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelEvento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(282, 282, 282)
                .addComponent(jButtonRealizarReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelTituloReservaSalon)
                .addGap(210, 210, 210))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(labelTituloReservaSalon)
                .addGap(27, 27, 27)
                .addComponent(jPanelDatosPersonalesReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRealizarReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRealizarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRealizarReservaActionPerformed
        String texto1, texto2;
        boolean todoCorrecto = true;

        texto1 = jTextFieldNombre.getText();
        texto2 = jTextFieldTelefono.getText();

        if (texto1.isEmpty()) {
            todoCorrecto = false;
            JOptionPane.showMessageDialog(this, "El campo 'Nombre' es obligatorio.",
                    "Error", JOptionPane.ERROR_MESSAGE);
        } else if (texto2.isEmpty()) {
            todoCorrecto = false;
            JOptionPane.showMessageDialog(this, "El campo 'Teléfono' es obligatorio.",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }

        if (todoCorrecto) {
            int res = JOptionPane.showConfirmDialog(this, "¿Son los datos correctos?", "Confirmación de datos", JOptionPane.YES_NO_OPTION);
            if (res == JOptionPane.YES_OPTION) {
                reservaRealizada = true;
                dispose(); // En este punto volvemos a PantallaPrincipal
            }
        }
    }//GEN-LAST:event_jButtonRealizarReservaActionPerformed

    public Reserva obtenerValoresFormulario() {
        // Como el spinner no da un LocalDate tenemos que convertirlo
        Date dateValue = (Date) jSpinnerFecha.getValue();   // Primero cogemos el valor y lo casteamos a Date
        Instant instant = dateValue.toInstant();            // Pasamos el Date a un momento en el tiempo
        ZoneId zoneId = ZoneId.systemDefault();             // Ese Obtenemos la zona del ordenador
        LocalDate localDate = instant.atZone(zoneId).toLocalDate(); // Convertimos el instant en un LocalDate ajustándolo
        // a la zona horaria especificada

        // guardamos los elementos seleccionados en caso de que haya más de uno
        List<String> elementosSeleccionados = jListTipoCocina.getSelectedValuesList();

        // Como en el comboBox aparec en minúscula hacemos el cambio a mayúcula para que coincida con el enumerado
        String tipoEventoSeleccionado = ((String) jComboBoxTipoEvento.getSelectedItem()).toUpperCase();
        TipoEvento tipoEvento = TipoEvento.valueOf(tipoEventoSeleccionado);

        Reserva reserva = new Reserva(jTextFieldNombre.getText(),
                Integer.parseInt(jTextFieldTelefono.getText()),
                (int) jSpinnerNumeroDias.getValue(),
                (int) jSpinnerNumeroHabitaciones.getValue(),
                localDate,
                (int) jSpinnerNumeroAsistentes.getValue(),
                elementosSeleccionados,
                tipoEvento,
                (int) jSpinnerNumeroAsistentes.getValue(),
                jRadioButtonSiHabitaciones.isSelected());
        return reserva;
    }

    public boolean isReservaRealizada() {
        return reservaRealizada;
    }

    private void jComboBoxTipoEventoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxTipoEventoItemStateChanged
        String seleccion;

        seleccion = jComboBoxTipoEvento.getSelectedItem().toString();

        if (EVENTO.equals(seleccion)) {
            labelJornadasCongreso.setEnabled(true);
            SpinnerJornadasCongreso.setEnabled(true);
            labelAsistentes.setEnabled(true);
            jRadioButtonSiHabitaciones.setEnabled(true);
            jRadioButtonNoHabitaciones.setEnabled(true);
        } else {
            labelJornadasCongreso.setEnabled(false);
            SpinnerJornadasCongreso.setEnabled(false);
            labelAsistentes.setEnabled(false);
            jRadioButtonSiHabitaciones.setEnabled(false);
            jRadioButtonNoHabitaciones.setEnabled(false);
        }

    }//GEN-LAST:event_jComboBoxTipoEventoItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaSecundaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaSecundaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaSecundaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaSecundaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PantallaSecundaria dialog = new PantallaSecundaria(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner SpinnerJornadasCongreso;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonRealizarReserva;
    private javax.swing.JComboBox<String> jComboBoxTipoEvento;
    private javax.swing.JList<String> jListTipoCocina;
    private javax.swing.JPanel jPanelDatosPersonalesReserva;
    private javax.swing.JPanel jPanelEvento;
    private javax.swing.JRadioButton jRadioButtonNoHabitaciones;
    private javax.swing.JRadioButton jRadioButtonSiHabitaciones;
    private javax.swing.JScrollPane jScrollPaneTipoCocina;
    private javax.swing.JSpinner jSpinnerFecha;
    private javax.swing.JSpinner jSpinnerNumeroAsistentes;
    private javax.swing.JSpinner jSpinnerNumeroDias;
    private javax.swing.JSpinner jSpinnerNumeroHabitaciones;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldTelefono;
    private javax.swing.JLabel labelAsistentes;
    private javax.swing.JLabel labelDatosPersonalesReserva;
    private javax.swing.JLabel labelEvento;
    private javax.swing.JLabel labelFechaEvento;
    private javax.swing.JLabel labelJornadasCongreso;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelNumeroAsistentes;
    private javax.swing.JLabel labelNumeroDias;
    private javax.swing.JLabel labelNumeroHabitaciones;
    private javax.swing.JLabel labelTelefono;
    private javax.swing.JLabel labelTipoCocina;
    private javax.swing.JLabel labelTipoEvento;
    private javax.swing.JLabel labelTituloReservaSalon;
    // End of variables declaration//GEN-END:variables
}
