package vista;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.time.LocalDate;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import modelo.Reserva;
import modelo.TipoEvento;

public class PantallaPrincipal extends javax.swing.JFrame {

    public PantallaPrincipal() {
        initComponents();

        // Lo ideal sería añadir esto en initComponents(), pero al estar bloqueado lo añado aquí
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
        int width = this.getSize().width;
        int height = this.getSize().height;
        int xPos = (pantalla.width - width) / 2;
        int yPos = (pantalla.height - height) / 2;
        this.setLocation(xPos, yPos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTituloPantallaPrincipal = new javax.swing.JLabel();
        jPanelSalonesDisponibles = new javax.swing.JPanel();
        labelSalonesDisponibles = new javax.swing.JLabel();
        ButtonSalonHabana = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("La Habana");
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));

        jLabelTituloPantallaPrincipal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelTituloPantallaPrincipal.setText("GESTIÓN HOTELERA LA HABANA");

        labelSalonesDisponibles.setText("Salones disponibles");

        ButtonSalonHabana.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/salonLaHabanaOriginal.png"))); // NOI18N
        ButtonSalonHabana.setToolTipText("Salón La Habana");
        ButtonSalonHabana.setBorder(null);
        ButtonSalonHabana.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/salonLaHabanaMini.png"))); // NOI18N
        ButtonSalonHabana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSalonHabanaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSalonesDisponiblesLayout = new javax.swing.GroupLayout(jPanelSalonesDisponibles);
        jPanelSalonesDisponibles.setLayout(jPanelSalonesDisponiblesLayout);
        jPanelSalonesDisponiblesLayout.setHorizontalGroup(
            jPanelSalonesDisponiblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSalonesDisponiblesLayout.createSequentialGroup()
                .addGroup(jPanelSalonesDisponiblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSalonesDisponiblesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelSalonesDisponibles))
                    .addGroup(jPanelSalonesDisponiblesLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(ButtonSalonHabana)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSalonesDisponiblesLayout.setVerticalGroup(
            jPanelSalonesDisponiblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSalonesDisponiblesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelSalonesDisponibles)
                .addGap(32, 32, 32)
                .addComponent(ButtonSalonHabana, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        jMenu1.setText("Inicio");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Salones disponibles");

        jMenuItem1.setText("Salón Habana");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelSalonesDisponibles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(230, Short.MAX_VALUE)
                .addComponent(jLabelTituloPantallaPrincipal)
                .addGap(213, 213, 213))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabelTituloPantallaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelSalonesDisponibles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        PantallaSecundaria ps = new PantallaSecundaria(this, rootPaneCheckingEnabled);
        ps.setVisible(true);
        mostrarBienvenida(ps);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void ButtonSalonHabanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSalonHabanaActionPerformed
        PantallaSecundaria ps = new PantallaSecundaria(this, rootPaneCheckingEnabled);
        ps.setVisible(true);
        mostrarBienvenida(ps);
    }//GEN-LAST:event_ButtonSalonHabanaActionPerformed

    private void mostrarBienvenida(PantallaSecundaria ps) {
        if (ps.isReservaRealizada()) {
            Reserva reserva = ps.obtenerValoresFormulario();
            String nombre = reserva.getNombre();
            int telefono = reserva.getTelefono();
            int numeroDias = reserva.getNumeroDias();
            int numeroHabitaciones = reserva.getNumeroHabitaciones();
            LocalDate fecha = reserva.getFechaEvento();
            int numeroAsistentesEvento = reserva.getNumeroAsistentesEvento();
            List<String> tipoCocina = reserva.getTipoCocina();
            TipoEvento tipoEvento = reserva.getTipoEvento();
            int numeroJornadasCongreso = reserva.getNumeroJornadasCongreso();
            boolean asistentesNecesitanHabitaciones = reserva.isAsistentesNecesitanHabitaciones();

            // Construimos el mensaje que vamos a mostrar en el OptionPane
            StringBuilder mensaje = new StringBuilder();
            mensaje.append("Gracias por su reserva, ").append(nombre).append("\n");
            mensaje.append("La información de su reserva es:\n");
            mensaje.append("Teléfono: ").append(telefono).append("\n");
            mensaje.append("Número de días: ").append(numeroDias).append("\n");
            mensaje.append("Número de habitaciones: ").append(numeroHabitaciones).append("\n");
            mensaje.append("Fecha del evento: ").append(fecha).append("\n");
            mensaje.append("Número de asistentes al evento: ").append(numeroAsistentesEvento).append("\n");
            mensaje.append("Tipo de cocina: ").append(tipoCocina).append("\n");
            mensaje.append("Tipo de evento: ").append(tipoEvento).append("\n");
            mensaje.append("Número de jornadas de congreso: ").append(numeroJornadasCongreso).append("\n");
            mensaje.append("¿Los asistentes necesitan habitaciones? ").append(asistentesNecesitanHabitaciones ? "Sí" : "No");

            JOptionPane.showMessageDialog(this, mensaje.toString(), "Mensaje de bienvenida", JOptionPane.PLAIN_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonSalonHabana;
    private javax.swing.JLabel jLabelTituloPantallaPrincipal;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanelSalonesDisponibles;
    private javax.swing.JLabel labelSalonesDisponibles;
    // End of variables declaration//GEN-END:variables
}
